In [ ]:
import pandas as pd 
import numpy as np
import os
import requests
from dotenv import load_dotenv
import pyarrow

load_dotenv()
api_key = os.getenv('FMP_API_KEY')

In [10]:
import requests
response = requests.get(
    f'https://financialmodelingprep.com/stable/balance-sheet-statement?symbol=AAPL&apikey={api_key}'

)

data = response.json()

In [11]:
data_df = pd.DataFrame(data)
data_df

,date,symbol,reportedCurrency,cik,filingDate,acceptedDate,fiscalYear,period,cashAndCashEquivalents,shortTermInvestments,...,additionalPaidInCapital,accumulatedOtherComprehensiveIncomeLoss,otherTotalStockholdersEquity,totalStockholdersEquity,totalEquity,minorityInterest,totalLiabilitiesAndTotalEquity,totalInvestments,totalDebt,netDebt
0,2025-09-27,AAPL,USD,0000320193,2025-10-31,2025-10-31 06:01:26,2025,FY,33539000000,21158000000,...,0,-5571000000,0,73733000000,73733000000,0,359241000000,98881000000,112377000000,78838000000
1,2024-09-28,AAPL,USD,0000320193,2024-11-01,2024-11-01 06:01:36,2024,FY,29943000000,35228000000,...,0,-7172000000,0,56950000000,56950000000,0,364980000000,126707000000,119059000000,89116000000
2,2023-09-30,AAPL,USD,0000320193,2023-11-03,2023-11-02 18:08:27,2023,FY,29965000000,31590000000,...,0,-11452000000,0,62146000000,62146000000,0,352583000000,132134000000,123930000000,93965000000
3,2022-09-24,AAPL,USD,0000320193,2022-10-28,2022-10-27 18:01:14,2022,FY,23646000000,24658000000,...,0,-11109000000,0,50672000000,50672000000,0,352755000000,145463000000,132480000000,108834000000
4,2021-09-25,AAPL,USD,0000320193,2021-10-29,2021-10-28 18:04:28,2021,FY,34940000000,27699000000,...,0,163000000,0,63090000000,63090000000,0,351002000000,155576000000,136522000000,101582000000

In [24]:
bs = data_df

In [45]:
cf_response = requests.get(
    f'https://financialmodelingprep.com/stable/cash-flow-statement?symbol=AAPL&apikey={api_key}'
)

cf_data = cf_response.json()
cf_data

[{'date': '2025-09-27',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2025-10-31',
  'acceptedDate': '2025-10-31 06:01:26',
  'fiscalYear': '2025',
  'period': 'FY',
  'netIncome': 112010000000,
  'depreciationAndAmortization': 11698000000,
  'deferredIncomeTax': 0,
  'stockBasedCompensation': 12863000000,
  'changeInWorkingCapital': -25000000000,
  'accountsReceivables': -6682000000,
  'inventory': 1400000000,
  'accountsPayables': 902000000,
  'otherWorkingCapital': -20620000000,
  'otherNonCashItems': -89000000,
  'netCashProvidedByOperatingActivities': 111482000000,
  'investmentsInPropertyPlantAndEquipment': -12715000000,
  'acquisitionsNet': 0,
  'purchasesOfInvestments': -24407000000,
  'salesMaturitiesOfInvestments': 53797000000,
  'otherInvestingActivities': -1480000000,
  'netCashProvidedByInvestingActivities': 15195000000,
  'netDebtIssuance': -8483000000,
  'longTermNetDebtIssuance': -6451000000,
  'shortTermNetDebtIssuance': -2032000000,
  'netStockIssuance': -90711000000,
  'netCommonStockIssuance': -90711000000,
  'commonStockIssuance': 0,
  'commonStockRepurchased': -90711000000,
  'netPreferredStockIssuance': 0,
  'netDividendsPaid': -15421000000,
  'commonDividendsPaid': -15421000000,
  'preferredDividendsPaid': 0,
  'otherFinancingActivities': -6071000000,
  'netCashProvidedByFinancingActivities': -120686000000,
  'effectOfForexChangesOnCash': 0,
  'netChangeInCash': 5991000000,
  'cashAtEndOfPeriod': 35934000000,
  'cashAtBeginningOfPeriod': 29943000000,
  'operatingCashFlow': 111482000000,
  'capitalExpenditure': -12715000000,
  'freeCashFlow': 98767000000,
  'incomeTaxesPaid': 43369000000,
  'interestPaid': 0},
 {'date': '2024-09-28',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2024-11-01',
  'acceptedDate': '2024-11-01 06:01:36',
  'fiscalYear': '2024',
  'period': 'FY',
  'netIncome': 93736000000,
  'depreciationAndAmortization': 11445000000,
  'deferredIncomeTax': 0,
  'stockBasedCompensation': 11688000000,
  'changeInWorkingCapital': 3651000000,
  'accountsReceivables': -5144000000,
  'inventory': -1046000000,
  'accountsPayables': 6020000000,
  'otherWorkingCapital': 3821000000,
  'otherNonCashItems': -2266000000,
  'netCashProvidedByOperatingActivities': 118254000000,
  'investmentsInPropertyPlantAndEquipment': -9447000000,
  'acquisitionsNet': 0,
  'purchasesOfInvestments': -48656000000,
  'salesMaturitiesOfInvestments': 62346000000,
  'otherInvestingActivities': -1308000000,
  'netCashProvidedByInvestingActivities': 2935000000,
  'netDebtIssuance': -5998000000,
  'longTermNetDebtIssuance': -9958000000,
  'shortTermNetDebtIssuance': 3960000000,
  'netStockIssuance': -94949000000,
  'netCommonStockIssuance': -94949000000,
  'commonStockIssuance': 0,
  'commonStockRepurchased': -94949000000,
  'netPreferredStockIssuance': 0,
  'netDividendsPaid': -15234000000,
  'commonDividendsPaid': -15234000000,
  'preferredDividendsPaid': 0,
  'otherFinancingActivities': -5802000000,
  'netCashProvidedByFinancingActivities': -121983000000,
  'effectOfForexChangesOnCash': 0,
  'netChangeInCash': -794000000,
  'cashAtEndOfPeriod': 29943000000,
  'cashAtBeginningOfPeriod': 30737000000,
  'operatingCashFlow': 118254000000,
  'capitalExpenditure': -9447000000,
  'freeCashFlow': 108807000000,
  'incomeTaxesPaid': 26102000000,
  'interestPaid': 0},
 {'date': '2023-09-30',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2023-11-03',
  'acceptedDate': '2023-11-02 18:08:27',
  'fiscalYear': '2023',
  'period': 'FY',
  'netIncome': 96995000000,
  'depreciationAndAmortization': 11519000000,
  'deferredIncomeTax': 0,
  'stockBasedCompensation': 10833000000,
  'changeInWorkingCapital': -6577000000,
  'accountsReceivables': -417000000,
  'inventory': -1618000000,
  'accountsPayables': -1889000000,
  'otherWorkingCapital': -2653000000,
  'otherNonCashItems': -2227000000,
  'netCashProvidedByOperatingActivities': 110543000000,
  'investmentsInPropertyPlantAndEquipment': -10959000000,
  'acquisitionsNet': 0,
  'purchasesOfInvestments': -29513000000,
  'salesMaturitiesOfInvestments': 45514000000,
  'otherInvestingActivities': -1337000000,
  'netCashProvidedByInvestingActivities': 3705000000,
  'netDebtIssuance': -9901000000,
  'longTermNetDebtIssuance': -5923000000,
  'shortTermNetDebtIssuance': -3978000000,
  'netStockIssuance': -77550000000,
  'netCommonStockIssuance': -77550000000,
  'commonStockIssuance': 0,
  'commonStockRepurchased': -77550000000,
  'netPreferredStockIssuance': 0,
  'netDividendsPaid': -15025000000,
  'commonDividendsPaid': -15025000000,
  'preferredDividendsPaid': 0,
  'otherFinancingActivities': -6012000000,
  'netCashProvidedByFinancingActivities': -108488000000,
  'effectOfForexChangesOnCash': 0,
  'netChangeInCash': 5760000000,
  'cashAtEndOfPeriod': 30737000000,
  'cashAtBeginningOfPeriod': 24977000000,
  'operatingCashFlow': 110543000000,
  'capitalExpenditure': -10959000000,
  'freeCashFlow': 99584000000,
  'incomeTaxesPaid': 18679000000,
  'interestPaid': 3803000000},
 {'date': '2022-09-24',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2022-10-28',
  'acceptedDate': '2022-10-27 18:01:14',
  'fiscalYear': '2022',
  'period': 'FY',
  'netIncome': 99803000000,
  'depreciationAndAmortization': 11104000000,
  'deferredIncomeTax': 895000000,
  'stockBasedCompensation': 9038000000,
  'changeInWorkingCapital': 1200000000,
  'accountsReceivables': -9343000000,
  'inventory': 1484000000,
  'accountsPayables': 9448000000,
  'otherWorkingCapital': -389000000,
  'otherNonCashItems': 111000000,
  'netCashProvidedByOperatingActivities': 122151000000,
  'investmentsInPropertyPlantAndEquipment': -10708000000,
  'acquisitionsNet': -306000000,
  'purchasesOfInvestments': -76923000000,
  'salesMaturitiesOfInvestments': 67363000000,
  'otherInvestingActivities': -1780000000,
  'netCashProvidedByInvestingActivities': -22354000000,
  'netDebtIssuance': -123000000,
  'longTermNetDebtIssuance': -4078000000,
  'shortTermNetDebtIssuance': 3955000000,
  'netStockIssuance': -89402000000,
  'netCommonStockIssuance': -89402000000,
  'commonStockIssuance': 0,
  'commonStockRepurchased': -89402000000,
  'netPreferredStockIssuance': 0,
  'netDividendsPaid': -14841000000,
  'commonDividendsPaid': -14841000000,
  'preferredDividendsPaid': 0,
  'otherFinancingActivities': -6383000000,
  'netCashProvidedByFinancingActivities': -110749000000,
  'effectOfForexChangesOnCash': 0,
  'netChangeInCash': -10952000000,
  'cashAtEndOfPeriod': 24977000000,
  'cashAtBeginningOfPeriod': 35929000000,
  'operatingCashFlow': 122151000000,
  'capitalExpenditure': -10708000000,
  'freeCashFlow': 111443000000,
  'incomeTaxesPaid': 19573000000,
  'interestPaid': 2865000000},
 {'date': '2021-09-25',
  'symbol': 'AAPL',
  'reportedCurrency': 'USD',
  'cik': '0000320193',
  'filingDate': '2021-10-29',
  'acceptedDate': '2021-10-28 18:04:28',
  'fiscalYear': '2021',
  'period': 'FY',
  'netIncome': 94680000000,
  'depreciationAndAmortization': 11284000000,
  'deferredIncomeTax': -4774000000,
  'stockBasedCompensation': 7906000000,
  'changeInWorkingCapital': -4911000000,
  'accountsReceivables': -14028000000,
  'inventory': -2642000000,
  'accountsPayables': 12326000000,
  'otherWorkingCapital': -567000000,
  'otherNonCashItems': -147000000,
  'netCashProvidedByOperatingActivities': 104038000000,
  'investmentsInPropertyPlantAndEquipment': -11085000000,
  'acquisitionsNet': -33000000,
  'purchasesOfInvestments': -109558000000,
  'salesMaturitiesOfInvestments': 106483000000,
  'otherInvestingActivities': -352000000,
  'netCashProvidedByInvestingActivities': -14545000000,
  'netDebtIssuance': 12665000000,
  'longTermNetDebtIssuance': 11643000000,
  'shortTermNetDebtIssuance': 1022000000,
  'netStockIssuance': -84866000000,
  'netCommonStockIssuance': -84866000000,
  'commonStockIssuance': 1105000000,
  'commonStockRepurchased': -85971000000,
  'netPreferredStockIssuance': 0,
  'netDividendsPaid': -14467000000,
  'commonDividendsPaid': -14467000000,
  'preferredDividendsPaid': 0,
  'otherFinancingActivities': -6685000000,
  'netCashProvidedByFinancingActivities': -93353000000,
  'effectOfForexChangesOnCash': 0,
  'netChangeInCash': -3860000000,
  'cashAtEndOfPeriod': 35929000000,
  'cashAtBeginningOfPeriod': 39789000000,
  'operatingCashFlow': 104038000000,
  'capitalExpenditure': -11085000000,
  'freeCashFlow': 92953000000,
  'incomeTaxesPaid': 25385000000,
  'interestPaid': 2687000000}]

In [46]:
cf = pd.DataFrame(cf_data)
cf

,date,symbol,reportedCurrency,cik,filingDate,acceptedDate,fiscalYear,period,netIncome,depreciationAndAmortization,...,netCashProvidedByFinancingActivities,effectOfForexChangesOnCash,netChangeInCash,cashAtEndOfPeriod,cashAtBeginningOfPeriod,operatingCashFlow,capitalExpenditure,freeCashFlow,incomeTaxesPaid,interestPaid
0,2025-09-27,AAPL,USD,0000320193,2025-10-31,2025-10-31 06:01:26,2025,FY,112010000000,11698000000,...,-120686000000,0,5991000000,35934000000,29943000000,111482000000,-12715000000,98767000000,43369000000,0
1,2024-09-28,AAPL,USD,0000320193,2024-11-01,2024-11-01 06:01:36,2024,FY,93736000000,11445000000,...,-121983000000,0,-794000000,29943000000,30737000000,118254000000,-9447000000,108807000000,26102000000,0
2,2023-09-30,AAPL,USD,0000320193,2023-11-03,2023-11-02 18:08:27,2023,FY,96995000000,11519000000,...,-108488000000,0,5760000000,30737000000,24977000000,110543000000,-10959000000,99584000000,18679000000,3803000000
3,2022-09-24,AAPL,USD,0000320193,2022-10-28,2022-10-27 18:01:14,2022,FY,99803000000,11104000000,...,-110749000000,0,-10952000000,24977000000,35929000000,122151000000,-10708000000,111443000000,19573000000,2865000000
4,2021-09-25,AAPL,USD,0000320193,2021-10-29,2021-10-28 18:04:28,2021,FY,94680000000,11284000000,...,-93353000000,0,-3860000000,35929000000,39789000000,104038000000,-11085000000,92953000000,25385000000,2687000000

In [19]:
cf_cfo = cf['operatingCashFlow']
cf_capex = cf['capitalExpenditure']
cf_net_debt = cf['netDebtIssuance']
fcf = cf_cfo + cf_capex + cf_net_debt
fcf_df = pd.DataFrame(fcf)
fcf_df.columns = ['free_cash_flow']
fcf_df

   free_cash_flow
0    -14969000000
1     -7255000000
2     -4453000000
3     11601000000
4     26653000000

In [20]:
today_fcf = np.average(fcf_df['free_cash_flow'])
today_fcf

np.float64(2315400000.0)

In [25]:
roe = cf['netIncome'] / bs['totalEquity']
roe = pd.DataFrame(roe)
roe.columns = ['roe']
roe

        roe
0 -0.260847
1  0.029412
2  0.129003
3  0.392090
4  0.331257

In [26]:
avg_roe = np.average(roe['roe'])
avg_roe

np.float64(0.12418302172684197)

In [28]:
reinv_rate = (cf['netIncome'] + cf ['netDividendsPaid']) / cf['netIncome']
reinv_rate = pd.DataFrame(reinv_rate)
reinv_rate.columns = ['reinv_rate']
reinv_rate_avg = np.average(reinv_rate['reinv_rate'])
reinv_rate_avg

np.float64(0.3882043433098338)

In [39]:
growth = avg_roe * reinv_rate_avg
real_growth = 0
if growth > 0.05:
    real_growth = 0.05
elif growth < 0:
    real_growth = 0
else:
    real_growth = growth

In [40]:
cost_e = 0.1

In [41]:
real_growth

np.float64(0.04820838839969951)

In [42]:
dcf = (today_fcf * (1+real_growth)) + ((today_fcf * ((1+real_growth)**2))/(cost_e - real_growth))
dcf

np.float64(51547418399.60896)

In [33]:
mk_cap_response = requests.get(
    f'https://financialmodelingprep.com/stable/market-capitalization?symbol=AAPL&apikey={api_key}'
)
mkcap = mk_cap_response.json()
mkcap

[{'symbol': 'AAPL', 'date': '2025-11-14', 'marketCap': 4025226320730}]

In [43]:
market_cap = pd.DataFrame(mkcap)
market_cap

  symbol        date      marketCap
0   AAPL  2025-11-14  4025226320730

In [44]:
ir = dcf / market_cap['marketCap']
ir

0    0.012806
Name: marketCap, dtype: float64